# Generated by Django 5.1.3 on 2024-11-17 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_banners_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banners",
            options={"verbose_name_plural": "Banners"},
        ),
    ]
