# Generated by Django 5.1.3 on 2025-01-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_banners_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banners",
            options={},
        ),
    ]
